// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {update} from '../models';
import {model} from '../models';
import {config} from '../models';
import {main} from '../models';
import {search} from '../models';

export function AddApplications(arg1:Array<string>):Promise<app.ImportResult>;

export function Blur():Promise<void>;

export function BrowseApplications():Promise<Array<string>>;

export function CheckUpdate():Promise<update.Info>;

export function DeleteApplication(arg1:string):Promise<void>;

export function FrontendReady():Promise<void>;

export function GetCustomApplications():Promise<Array<model.AppItem>>;

export function GetHome():Promise<app.Home>;

export function GetSettings():Promise<config.Config>;

export function GetStatus():Promise<main.Status>;

export function Hide():Promise<void>;

export function InstallUpdate():Promise<void>;

export function Launch(arg1:string,arg2:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function Quit():Promise<void>;

export function RefreshIndex():Promise<void>;

export function Resize(arg1:number):Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function Search(arg1:string):Promise<Array<search.Result>>;

export function SetImportMode(arg1:boolean):Promise<void>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;

export function Show():Promise<void>;

export function Toggle():Promise<void>;
