// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blur() {
  return window['go']['main']['App']['Blur']();
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function Launch(arg1, arg2) {
  return window['go']['main']['App']['Launch'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshIndex() {
  return window['go']['main']['App']['RefreshIndex']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
