// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {search} from '../models';

export function Blur():Promise<void>;

export function FrontendReady():Promise<void>;

export function GetSettings():Promise<config.Config>;

export function GetStatus():Promise<main.Status>;

export function Hide():Promise<void>;

export function Launch(arg1:string,arg2:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function Quit():Promise<void>;

export function RefreshIndex():Promise<void>;

export function Resize(arg1:number):Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function Search(arg1:string):Promise<Array<search.Result>>;

export function Show():Promise<void>;

export function Toggle():Promise<void>;
