// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApplications(arg1) {
  return window['go']['main']['App']['AddApplications'](arg1);
}

export function Blur() {
  return window['go']['main']['App']['Blur']();
}

export function BrowseApplications() {
  return window['go']['main']['App']['BrowseApplications']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteApplication(arg1) {
  return window['go']['main']['App']['DeleteApplication'](arg1);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetCustomApplications() {
  return window['go']['main']['App']['GetCustomApplications']();
}

export function GetHome() {
  return window['go']['main']['App']['GetHome']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function Launch(arg1, arg2) {
  return window['go']['main']['App']['Launch'](arg1, arg2);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshIndex() {
  return window['go']['main']['App']['RefreshIndex']();
}

export function Resize(arg1) {
  return window['go']['main']['App']['Resize'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetImportMode(arg1) {
  return window['go']['main']['App']['SetImportMode'](arg1);
}

export function SetPinned(arg1, arg2) {
  return window['go']['main']['App']['SetPinned'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
